not_allow_by_console: "&8&l>> &c&lPolecenia helpop nie moża używać z konsoli"
usage: "&8&l>> &c&lPoprawne użycie: /helpop <wiadomość>"
helpop_msg_plr: "&8&l>> &c&lHELPOP: &e&l{SENDER} &8&l>> &a&l{MSG}"
helpop_msg_sender: "&8&l>> &c&lWysłano wiadomość na helpop: &a&l{MSG}"